// <auto-generated />
using System;
using Dierentuin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dierentuin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250324002115_AddedZooIdToEnclosure")]
    partial class AddedZooIdToEnclosure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalAnimal", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("PreyId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId", "PreyId");

                    b.HasIndex("PreyId");

                    b.ToTable("AnimalAnimal");
                });

            modelBuilder.Entity("Dierentuin.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAwake")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("ZooId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityPattern = 2,
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 2,
                            IsAwake = false,
                            Name = "Ottis",
                            SecurityRequirement = 2,
                            Size = 0,
                            SpaceRequirement = 45.193264691454019,
                            Species = "Incredible Soft Mouse"
                        },
                        new
                        {
                            Id = 2,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            DietaryClass = 0,
                            EnclosureId = 4,
                            IsAwake = true,
                            Name = "Stone",
                            SecurityRequirement = 0,
                            Size = 3,
                            SpaceRequirement = 31.594854863782611,
                            Species = "Small Fresh Soap"
                        },
                        new
                        {
                            Id = 3,
                            ActivityPattern = 0,
                            CategoryId = 3,
                            DietaryClass = 1,
                            EnclosureId = 4,
                            IsAwake = false,
                            Name = "Holden",
                            SecurityRequirement = 2,
                            Size = 1,
                            SpaceRequirement = 8.1866486963561336,
                            Species = "Intelligent Frozen Chicken"
                        },
                        new
                        {
                            Id = 4,
                            ActivityPattern = 0,
                            CategoryId = 2,
                            DietaryClass = 1,
                            EnclosureId = 1,
                            IsAwake = false,
                            Name = "Ubaldo",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 39.179955008238338,
                            Species = "Generic Granite Hat"
                        },
                        new
                        {
                            Id = 5,
                            ActivityPattern = 0,
                            CategoryId = 4,
                            DietaryClass = 1,
                            EnclosureId = 3,
                            IsAwake = false,
                            Name = "Beau",
                            SecurityRequirement = 1,
                            Size = 0,
                            SpaceRequirement = 24.463827750056687,
                            Species = "Awesome Wooden Chair"
                        },
                        new
                        {
                            Id = 6,
                            ActivityPattern = 1,
                            DietaryClass = 3,
                            EnclosureId = 3,
                            IsAwake = true,
                            Name = "Maida",
                            SecurityRequirement = 0,
                            Size = 4,
                            SpaceRequirement = 32.936638637482673,
                            Species = "Gorgeous Granite Chair"
                        },
                        new
                        {
                            Id = 7,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            DietaryClass = 4,
                            IsAwake = false,
                            Name = "Ron",
                            SecurityRequirement = 0,
                            Size = 2,
                            SpaceRequirement = 5.8598056935774903,
                            Species = "Fantastic Metal Keyboard"
                        },
                        new
                        {
                            Id = 8,
                            ActivityPattern = 2,
                            DietaryClass = 0,
                            EnclosureId = 1,
                            IsAwake = false,
                            Name = "Winifred",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 40.037743140472138,
                            Species = "Tasty Concrete Chair"
                        },
                        new
                        {
                            Id = 9,
                            ActivityPattern = 0,
                            CategoryId = 3,
                            DietaryClass = 4,
                            EnclosureId = 3,
                            IsAwake = true,
                            Name = "Eunice",
                            SecurityRequirement = 1,
                            Size = 0,
                            SpaceRequirement = 42.366784166115913,
                            Species = "Handcrafted Granite Table"
                        },
                        new
                        {
                            Id = 10,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            DietaryClass = 0,
                            IsAwake = true,
                            Name = "Annamae",
                            SecurityRequirement = 0,
                            Size = 5,
                            SpaceRequirement = 19.726876013732753,
                            Species = "Fantastic Steel Mouse"
                        },
                        new
                        {
                            Id = 11,
                            ActivityPattern = 0,
                            DietaryClass = 4,
                            IsAwake = true,
                            Name = "Caterina",
                            SecurityRequirement = 0,
                            Size = 4,
                            SpaceRequirement = 13.682969977824321,
                            Species = "Small Cotton Chicken"
                        },
                        new
                        {
                            Id = 12,
                            ActivityPattern = 0,
                            CategoryId = 4,
                            DietaryClass = 4,
                            EnclosureId = 4,
                            IsAwake = false,
                            Name = "Gunner",
                            SecurityRequirement = 0,
                            Size = 0,
                            SpaceRequirement = 40.568483333383099,
                            Species = "Tasty Concrete Chicken"
                        },
                        new
                        {
                            Id = 13,
                            ActivityPattern = 2,
                            CategoryId = 2,
                            DietaryClass = 2,
                            IsAwake = true,
                            Name = "Tavares",
                            SecurityRequirement = 0,
                            Size = 0,
                            SpaceRequirement = 43.480951248312728,
                            Species = "Intelligent Metal Bike"
                        },
                        new
                        {
                            Id = 14,
                            ActivityPattern = 2,
                            CategoryId = 5,
                            DietaryClass = 1,
                            IsAwake = false,
                            Name = "Mustafa",
                            SecurityRequirement = 0,
                            Size = 2,
                            SpaceRequirement = 48.84502351692494,
                            Species = "Licensed Plastic Ball"
                        },
                        new
                        {
                            Id = 15,
                            ActivityPattern = 1,
                            CategoryId = 2,
                            DietaryClass = 2,
                            EnclosureId = 4,
                            IsAwake = true,
                            Name = "Alexie",
                            SecurityRequirement = 1,
                            Size = 3,
                            SpaceRequirement = 43.612421563965235,
                            Species = "Tasty Rubber Bacon"
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zoogdieren"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vogels"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reptielen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Insecten"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amfibieën"
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("HabitatType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 2,
                            HabitatType = 8,
                            Name = "Verblijf Tools, Games & Games",
                            SecurityLevel = 2,
                            Size = 297.63126551001062,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 2,
                            Climate = 1,
                            HabitatType = 4,
                            Name = "Verblijf Home, Garden & Games",
                            SecurityLevel = 2,
                            Size = 422.86658100267965,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 3,
                            Climate = 1,
                            HabitatType = 8,
                            Name = "Verblijf Shoes & Industrial",
                            SecurityLevel = 0,
                            Size = 137.66378554093046,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 4,
                            Climate = 2,
                            HabitatType = 1,
                            Name = "Verblijf Sports, Garden & Beauty",
                            SecurityLevel = 0,
                            Size = 117.37705303934428,
                            ZooId = 1
                        });
                });

            modelBuilder.Entity("Dierentuin.Models.Zoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zoos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bogus Dierentuin"
                        });
                });

            modelBuilder.Entity("AnimalAnimal", b =>
                {
                    b.HasOne("Dierentuin.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dierentuin.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("PreyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dierentuin.Models.Animal", b =>
                {
                    b.HasOne("Dierentuin.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Dierentuin.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId");

                    b.HasOne("Dierentuin.Models.Zoo", null)
                        .WithMany("AllAnimals")
                        .HasForeignKey("ZooId");

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Dierentuin.Models.Enclosure", b =>
                {
                    b.HasOne("Dierentuin.Models.Zoo", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Dierentuin.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Dierentuin.Models.Zoo", b =>
                {
                    b.Navigation("AllAnimals");

                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
